### ISSUE TITLE
bayes_nn.ipynb: svgd_coin_results_alt initialized but unused

### ISSUE THREAD

**Issue by leocotteleer** [louissharrock/Coin-SVGD#1]
Hi Louis, thanks for releasing your code open source !

In the example _bayes_nn.ipynb_, the variable _svgd_coin_results_alt_ is initialized with zeros and is not modified after, which yields to an issue when calling the function _return_confidence_interval()_.

**Comment by louissharrock** [comment]
Thanks for pointing this out! It's now been resolved.
